// ============================================
// MAPA DE ÍCONES LUCIDE - EDITOR VISUAL DE MENU
// Centraliza todos os ícones disponíveis para o menu
// ============================================

import {
  LayoutDashboard,
  Users,
  Wallet,
  Building2,
  TrendingUp,
  Handshake,
  GraduationCap,
  FileText,
  LogOut,
  Settings,
  UserCog,
  BookOpen,
  Calendar,
  CreditCard,
  Calculator,
  Globe,
  ClipboardCheck,
  UserCheck,
  Brain,
  Link2,
  Shield,
  PlayCircle,
  Megaphone,
  Rocket,
  BarChart3,
  FolderOpen,
  PenTool,
  Monitor,
  MapPin,
  Code,
  User,
  Heart,
  Gauge,
  Activity,
  Zap,
  Crown,
  Sparkles,
  MessageSquareText,
  Stethoscope,
  Video,
  FileDown,
  Lightbulb,
  Network,
  HelpCircle,
  PenLine,
  Trophy,
  Medal,
  Star,
  MessageCircle,
  Radio,
  Eraser,
  Beaker,
  AtomIcon,
  Target,
  CalendarDays,
  Award,
  Home,
  Mail,
  Phone,
  Search,
  Bell,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Edit,
  Trash2,
  Plus,
  Minus,
  Check,
  X,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  Upload,
  Download,
  Share,
  Copy,
  Clipboard,
  Image,
  Camera,
  Mic,
  Music,
  Film,
  Tv,
  Headphones,
  Printer,
  Save,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Maximize,
  Minimize,
  ExternalLink,
  Layers,
  Grid,
  List,
  Table,
  PieChart,
  LineChart,
  DollarSign,
  Euro,
  Percent,
  Hash,
  AtSign,
  Send,
  Package,
  ShoppingCart,
  ShoppingBag,
  Store,
  Truck,
  MapPinned,
  Compass,
  Navigation,
  Flame,
  Snowflake,
  Sun,
  Moon,
  Cloud,
  Umbrella,
  Wind,
  Droplets,
  ThermometerSun,
  Wifi,
  WifiOff,
  Bluetooth,
  Battery,
  BatteryCharging,
  Power,
  Plug,
  Cpu,
  Server,
  Database,
  HardDrive,
  Terminal,
  Bug,
  GitBranch,
  GitCommit,
  GitMerge,
  Github,
  Gitlab,
  Linkedin,
  Twitter,
  Facebook,
  Instagram,
  Youtube,
  type LucideIcon,
  Menu,
  MoreHorizontal,
  MoreVertical,
  Filter,
  SlidersHorizontal,
  Palette,
  Paintbrush,
  Pencil,
  Scissors,
  Ruler,
  Wrench,
  Hammer,
  Cog,
  Key,
  Fingerprint,
  QrCode,
  Barcode,
  Tag,
  Tags,
  Bookmark,
  BookMarked,
  Flag,
  AlertCircle,
  AlertTriangle,
  Info,
  CircleHelp,
  CircleCheck,
  CircleX,
  Circle,
  Square,
  Triangle,
  Hexagon,
  Octagon,
  Pentagon,
  Diamond,
  Boxes,
  Box,
  Inbox,
  Archive,
  ArchiveRestore,
  FolderPlus,
  FolderMinus,
  FolderOpen as FolderOpenIcon,
  FileCode,
  FileImage,
  FileVideo,
  FileAudio,
  FilePlus,
  FileMinus,
  FileCheck,
  FileX,
  Files,
  Folder,
  Layout,
  LayoutGrid,
  LayoutList,
  LayoutTemplate,
  Blocks,
  Component,
  Puzzle,
  Shapes,
  Wand2,
  Sparkle,
  PartyPopper,
  Gift,
  Cake,
  Candy,
  Coffee,
  Wine,
  Beer,
  Utensils,
  ChefHat,
  Apple,
  Carrot,
  Leaf,
  TreePine,
  Flower,
  Bird,
  Cat,
  Dog,
  Fish,
  Rabbit,
  Squirrel,
  Turtle,
  Skull,
  Ghost,
  Footprints,
  Glasses,
  Watch,
  Shirt,
  ShoppingBasket,
  Receipt,
  Banknote,
  Coins,
  PiggyBank,
  Landmark,
  Building,
  Factory,
  Hotel,
  School,
  Library,
  Church,
  Hospital,
  Pill,
  Syringe,
  Stethoscope as StethoscopeIcon,
  Microscope,
  TestTube,
  TestTubes,
  Dna,
  Scale,
  Gavel,
  BadgeCheck,
  BadgeAlert,
  BadgeHelp,
  BadgeInfo,
  BadgeMinus,
  BadgePlus,
  BadgeX,
  Verified,
  ShieldCheck,
  ShieldAlert,
  ShieldQuestion,
  ShieldOff,
  LockKeyhole,
  UnlockKeyhole,
  KeyRound,
  Scan,
  ScanLine,
  ScanFace,
  Crosshair,
  Focus,
  Aperture,
  Ratio,
  Contrast,
  SunDim,
  Sunrise,
  Sunset,
  MoonStar,
  Stars,
  Orbit,
  Satellite,
  Rocket as RocketIcon,
  Plane,
  PlaneTakeoff,
  PlaneLanding,
  Car,
  Bus,
  Train,
  Ship,
  Bike,
  Footprints as FootprintsIcon,
  Accessibility,
  Baby,
  PersonStanding,
  VenetianMask,
  Drama,
  Gamepad,
  Gamepad2,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Joystick,
  Swords,
  Crown as CrownIcon,
  Gem,
  Coins as CoinsIcon,
} from "lucide-react";

// Mapa completo de ícones disponíveis
export const ICON_MAP: Record<string, LucideIcon> = {
  // Navegação e UI
  LayoutDashboard,
  Menu,
  Home,
  Search,
  Bell,
  Settings,
  Cog,
  MoreHorizontal,
  MoreVertical,
  Filter,
  SlidersHorizontal,
  
  // Usuários e Perfil
  Users,
  User,
  UserCog,
  UserCheck,
  PersonStanding,
  Baby,
  Accessibility,
  
  // Finanças
  Wallet,
  DollarSign,
  Euro,
  CreditCard,
  Banknote,
  Coins: CoinsIcon,
  PiggyBank,
  TrendingUp,
  Calculator,
  Receipt,
  
  // Negócios
  Building2,
  Building,
  Factory,
  Store,
  Handshake,
  Briefcase: FolderOpen,
  Package,
  ShoppingCart,
  ShoppingBag,
  Truck,
  
  // Educação
  GraduationCap,
  BookOpen,
  School,
  Library,
  Brain,
  Lightbulb,
  PenTool,
  Pencil,
  PenLine,
  
  // Arquivos e Documentos
  FileText,
  Files,
  Folder,
  FolderOpen: FolderOpenIcon,
  FolderPlus,
  FileCode,
  FileImage,
  FileVideo,
  FileAudio,
  FilePlus,
  FileDown,
  Upload,
  Download,
  Archive,
  
  // Calendário e Tempo
  Calendar,
  CalendarDays,
  Clock: Activity,
  Watch,
  
  // Comunicação
  Mail,
  MessageCircle,
  MessageSquareText,
  Phone,
  Send,
  Radio,
  
  // Mídia
  Video,
  Image,
  Camera,
  Mic,
  Music,
  Film,
  Tv,
  Headphones,
  PlayCircle,
  
  // Desenvolvimento
  Code,
  Terminal,
  Bug,
  GitBranch,
  GitCommit,
  GitMerge,
  Github,
  Database,
  Server,
  Cpu,
  
  // Segurança
  Shield,
  ShieldCheck,
  ShieldAlert,
  Lock,
  Unlock,
  Key,
  KeyRound,
  Fingerprint,
  
  // Status e Alertas
  AlertCircle,
  AlertTriangle,
  Info,
  CircleHelp,
  CircleCheck,
  CircleX,
  Check,
  X,
  
  // Ações
  Edit,
  Trash2,
  Plus,
  Minus,
  Save,
  RefreshCw,
  RotateCcw,
  Copy,
  Share,
  ExternalLink,
  Link2,
  
  // Navegação Direcional
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  
  // Visualização
  Eye,
  EyeOff,
  Maximize,
  Minimize,
  Layers,
  Grid,
  List,
  Table,
  Layout,
  LayoutGrid,
  
  // Gráficos e Métricas
  BarChart3,
  PieChart,
  LineChart,
  Activity,
  Gauge,
  Target,
  
  // Marketing e Lançamento
  Megaphone,
  Rocket: RocketIcon,
  Zap,
  Sparkles,
  Sparkle,
  Crown: CrownIcon,
  Star,
  Trophy,
  Medal,
  Award,
  
  // Mapas e Localização
  Globe,
  MapPin,
  MapPinned,
  Compass,
  Navigation,
  Monitor,
  
  // Saúde e Ciência
  Stethoscope: StethoscopeIcon,
  Hospital,
  Pill,
  Microscope,
  TestTube,
  Beaker,
  AtomIcon,
  Dna,
  
  // Diversos
  Heart,
  Bookmark,
  Tag,
  Tags,
  Flag,
  ClipboardCheck,
  Clipboard,
  Network,
  HelpCircle,
  Eraser,
  LogOut,
  Printer,
  QrCode,
  Verified,
  BadgeCheck,
  Gem,
  Gift,
  PartyPopper,
  Wand2,
  Puzzle,
  Component,
  Blocks,
  Shapes,
  
  // Social
  Linkedin,
  Twitter,
  Facebook,
  Instagram,
  Youtube,
  
  // Natureza
  Sun,
  Moon,
  MoonStar,
  Cloud,
  Flame,
  Leaf,
  TreePine,
  Flower,
  
  // Transporte
  Car,
  Bus,
  Train,
  Plane,
  Ship,
  Bike,
  
  // Alimentação
  Coffee,
  Utensils,
  Apple,
};

// Lista de ícones para o picker (ordenados por categoria)
export const ICON_CATEGORIES = {
  "Navegação": ["LayoutDashboard", "Menu", "Home", "Search", "Settings", "Filter"],
  "Usuários": ["Users", "User", "UserCog", "UserCheck", "GraduationCap"],
  "Finanças": ["Wallet", "DollarSign", "CreditCard", "TrendingUp", "Calculator", "Receipt", "Banknote"],
  "Negócios": ["Building2", "Store", "Handshake", "Package", "ShoppingCart", "Truck"],
  "Educação": ["BookOpen", "Brain", "Lightbulb", "PenTool", "School", "Library"],
  "Arquivos": ["FileText", "Folder", "FolderOpen", "Archive", "Upload", "Download"],
  "Calendário": ["Calendar", "CalendarDays"],
  "Comunicação": ["Mail", "MessageCircle", "MessageSquareText", "Phone", "Send", "Radio"],
  "Mídia": ["Video", "PlayCircle", "Image", "Camera", "Mic", "Music", "Film"],
  "Desenvolvimento": ["Code", "Terminal", "Bug", "GitBranch", "Database", "Server"],
  "Segurança": ["Shield", "ShieldCheck", "Lock", "Key", "Fingerprint"],
  "Status": ["AlertCircle", "AlertTriangle", "Info", "Check", "X", "CircleCheck"],
  "Gráficos": ["BarChart3", "PieChart", "LineChart", "Activity", "Gauge", "Target"],
  "Marketing": ["Megaphone", "Rocket", "Zap", "Sparkles", "Crown", "Star", "Trophy", "Award"],
  "Mapas": ["Globe", "MapPin", "Compass", "Monitor", "Navigation"],
  "Saúde": ["Stethoscope", "Beaker", "AtomIcon", "Microscope", "TestTube"],
  "Diversos": ["Heart", "Bookmark", "Tag", "Flag", "ClipboardCheck", "Link2", "Network", "HelpCircle"],
};

// Função para obter componente de ícone pelo nome
export function getIconComponent(name: string): LucideIcon | null {
  return ICON_MAP[name] || null;
}

// Lista flat de todos os nomes de ícones
export const ALL_ICON_NAMES = Object.keys(ICON_MAP);

// Buscar ícones por termo
export function searchIcons(term: string): string[] {
  if (!term) return ALL_ICON_NAMES.slice(0, 50); // Retorna os primeiros 50 se não houver busca
  
  const lowerTerm = term.toLowerCase();
  return ALL_ICON_NAMES.filter(name => 
    name.toLowerCase().includes(lowerTerm)
  );
}
