-- =====================================================
-- FASE 1: REVOGAÇÃO DE EXECUTE ANON EM FUNÇÕES CRÍTICAS
-- Data: 2026-01-22 | Lote 1/4 - Funções A-C
-- =====================================================

-- === A ===
REVOKE EXECUTE ON FUNCTION public.add_user_xp(p_user_id uuid, p_amount integer, p_source text, p_source_id uuid, p_description text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_get_all_devices(p_limit integer, p_offset integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_get_all_devices(p_limit integer, p_offset integer, p_only_active boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_get_blocked_attempts(p_limit integer, p_only_unresolved boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_get_device_stats() FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_list_beta_users() FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_requires_mfa(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.analyze_slow_queries() FROM anon;
REVOKE EXECUTE ON FUNCTION public.annihilate_all_questions() FROM anon;
REVOKE EXECUTE ON FUNCTION public.annihilate_import_batch(p_import_history_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.apply_chat_timeout(p_live_id uuid, p_user_id uuid, p_duration_minutes integer, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.apply_lesson_video_links(p_rows jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.apply_risk_score_decay() FROM anon;
REVOKE EXECUTE ON FUNCTION public.assert_role(_user_id uuid, _required_role text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.assign_owner_role() FROM anon;
REVOKE EXECUTE ON FUNCTION public.audit_financial_changes() FROM anon;
REVOKE EXECUTE ON FUNCTION public.audit_invalid_cpfs() FROM anon;
REVOKE EXECUTE ON FUNCTION public.audit_rls_coverage() FROM anon;
REVOKE EXECUTE ON FUNCTION public.audit_rls_coverage_v2() FROM anon;
REVOKE EXECUTE ON FUNCTION public.audit_role_changes() FROM anon;
REVOKE EXECUTE ON FUNCTION public.audit_role_changes_v2() FROM anon;
REVOKE EXECUTE ON FUNCTION public.auto_cleanup_for_load() FROM anon;
REVOKE EXECUTE ON FUNCTION public.auto_cleanup_logs_48h() FROM anon;
REVOKE EXECUTE ON FUNCTION public.auto_cleanup_rate_limits() FROM anon;
REVOKE EXECUTE ON FUNCTION public.auto_create_beta_expiration() FROM anon;

-- === B ===
REVOKE EXECUTE ON FUNCTION public.ban_user_and_revoke_sessions(p_target_user_id uuid, p_reason text, p_banned_by uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.batch_update_lesson_positions(updates jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.block_ip_auto(p_ip_address inet, p_reason text, p_duration_hours integer) FROM anon;

-- === C ===
REVOKE EXECUTE ON FUNCTION public.calculate_device_risk_score(p_user_id uuid, p_device_hash text, p_ip text, p_country text, p_user_agent text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.can_access_attachment(p_entity_type text, p_entity_id text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.can_access_resource(p_user_id uuid, p_resource_type text, p_resource_id uuid, p_action text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.can_access_sanctuary(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.can_access_url(p_url text, p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.can_access_url_v2(p_url text, p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.can_access_url_v3(p_url text, p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.can_access_url_v4(p_url text, p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.can_access_url_v5(p_url text, p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.can_edit_content(_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.can_manage_documents(_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.can_use_god_mode(_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.can_view_all_data(_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.can_view_financial(_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.can_view_personal(_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_active_session_exists(_email text, _session_token text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_advanced_rate_limit(p_identifier text, p_endpoint text, p_max_requests integer, p_window_seconds integer, p_block_seconds integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_and_update_overdue_expenses() FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_api_rate_limit(p_client_id text, p_endpoint text, p_limit integer, p_window_seconds integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_auth_before_login() FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_auth_enabled() FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_beta_access(_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_chat_rate_limit_v2(p_live_id uuid, p_user_id uuid, p_window_ms integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_deployment_gates() FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_device_limit(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_device_mfa_valid(_user_id uuid, _device_hash text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_is_owner() FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_is_owner_by_id(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_is_owner_email(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_mfa_valid(_user_id uuid, _action text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_password_reset_token(_token text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_rate_limit(p_operation text, p_max_requests integer, p_window_minutes integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_rate_limit_unified(p_identifier text, p_endpoint text, p_limit integer, p_window_seconds integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_rate_limit_v2(p_identifier text, p_endpoint text, p_max_requests integer, p_window_seconds integer, p_block_seconds integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_rate_limit_v3(p_identifier text, p_endpoint text, p_role text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_system_capacity() FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_url_access_v3(p_user_id uuid, p_url text, p_domain text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_url_access_with_mfa(p_user_id uuid, p_url text, p_domain text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_webhook_idempotency(p_provider text, p_event_id text, p_event_type text, p_payload jsonb, p_ip_address inet, p_signature_valid boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_webhook_idempotency_v2(p_provider text, p_event_id text, p_event_type text, p_payload jsonb, p_ip_address inet, p_signature_valid boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_webhook_idempotency_v3(p_provider text, p_event_id text, p_event_type text, p_payload jsonb, p_ip_address text, p_signature_valid boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_webhook_idempotency_v4(p_provider text, p_event_id text, p_event_type text, p_payload jsonb, p_ip_address text, p_signature_valid boolean, p_correlation_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.claim_next_event(p_consumer_name text, p_event_types event_name[]) FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_expired_2fa_codes() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_expired_mfa_verifications() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_expired_sessions() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_expired_sessions_v2() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_expired_sessions_v3() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_expired_signed_urls() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_expired_timeouts() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_expired_video_sessions() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_expired_video_sessions_omega() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_old_audit_logs() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_old_chat_messages() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_old_location_data() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_old_logs() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_old_rate_limits() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_old_rate_limits_v2() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_old_security_events() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_old_security_events(p_days integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_old_security_events_v2() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_old_security_logs() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_old_sensitive_data() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_old_video_logs() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_old_webhooks() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_rate_limits() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_rate_limits_v3() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_security_data() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_security_data_v3() FROM anon;
REVOKE EXECUTE ON FUNCTION public.complete_event(p_event_id bigint, p_success boolean, p_error_message text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.comprehensive_security_cleanup() FROM anon;
REVOKE EXECUTE ON FUNCTION public.consume_password_reset_token(_token text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.count_entity_attachments(p_entity_type text, p_entity_id text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.count_user_devices(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_critical_alert(p_alert_type text, p_severity text, p_title text, p_message text, p_threshold_value numeric, p_current_value numeric, p_metadata jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_password_reset_token(_email text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_ranking_snapshot(p_simulado_id uuid, p_snapshot_type text, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_rollback_point(p_version text, p_description text, p_git_commit text, p_is_stable boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_single_session(_ip_address text, _user_agent text, _device_type text, _browser text, _os text, _device_hash_from_server text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_user_session(p_device_hash text, p_device_type text, p_device_name text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_video_session(p_user_id uuid, p_lesson_id uuid, p_course_id uuid, p_provider text, p_provider_video_id text, p_ip_address text, p_user_agent text, p_device_fingerprint text, p_ttl_minutes integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_video_session_omega(p_user_id uuid, p_lesson_id uuid, p_provider text, p_provider_video_id text, p_ttl_minutes integer, p_watermark_text text, p_ip inet, p_user_agent text, p_device_fingerprint text, p_sanctum_immune boolean, p_sanctum_bypass_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.current_user_email() FROM anon;